const books = [
  {
    price: 10.5,
    rating: 5,
    title: "Atomic Habits:Proven Way To Build Good Habits",
    author: "661f178222f8964ff515e83b",
    reviews: 69.548,
    cover: "hard cover",
    image: "atomic-habits.jpg",
    printLength: 320,
    language: "English",
    PublicationDate: "16 April 2018",
    inStock: true,
  },
  {
    price: 14,
    rating: 5,
    title: "Confess",
    author: "661f178222f8964ff515e83b",
    reviews: 3.98,
    cover: "hard cover",
    image: "confess.jpg",
    printLength: 410,
    language: "English",
    PublicationDate: "1 March 2015",
    inStock: true,
  },
  {
    price: 9.05,
    rating: 5,
    title: "The Trouble With Hating You",
    author: "661f17a222f8964ff515e83d",
    reviews: 235,
    cover: "hard cover",
    image: "the-trouble-with-hating-you.jpg",
    printLength: 352,
    language: "English",
    PublicationDate: "1 June 2019",
    inStock: true,
  },
  {
    price: 16.45,
    rating: 4.5,
    title: "Hopeless",
    author: "661f17a222f8964ff515e83d",
    reviews: 1.587,
    cover: "hard cover",
    image: "hopeless.jpg",
    printLength: 416,
    language: "English",
    PublicationDate: "8 October 2012",
    inStock: true,
  },
  {
    price: 8,
    rating: 4,
    title: "trace",
    author: "661f17b922f8964ff515e83f",
    reviews: 8.661,
    cover: "hard cover",
    image: "rich-dad-poor-dad.jpg",
    printLength: 336,
    language: "English",
    PublicationDate: "27 April 2017",
    inStock: true,
  },
  {
    price: 21,
    rating: 3.5,
    title: "One True Loves",
    author: "661f17b922f8964ff515e83f",
    reviews: 2.421,
    cover: "hard cover",
    image: "one-true-love.jpg",
    printLength: 342,
    language: "English",
    PublicationDate: "17 July 2016",
    inStock: true,
  },
  {
    price: 11.05,
    rating: 4.5,
    title: "Think And Grow Rich",
    author: "661f17fc22f8964ff515e841",
    reviews: 57.521,
    cover: "hard cover",
    image: "think-and-grow-rich.jpg",
    printLength: 320,
    language: "English",
    PublicationDate: "1 September 2005",
    inStock: true,
  },
  {
    price: 7.05,
    rating: 4.5,
    title: "Never Split The Difference",
    author: "661f17fc22f8964ff515e841",
    reviews: 17.98,
    cover: "hard cover",
    image: "never-split-the-difference.jpg",
    printLength: 288,
    language: "English",
    PublicationDate: "23 March 2017",
    inStock: true,
  },
  {
    price: 12.58,
    rating: 5,
    title: "Good Vibes, Good Life",
    author: "661f3954d8592757e2c7fc11",
    reviews: 22.252,
    cover: "hard cover",
    image: "it-ends-with-us.jpg",
    printLength: 325,
    language: "English",
    PublicationDate: "4 December 2018",
    inStock: true,
  },
  {
    price: 5.98,
    rating: 4.5,
    title: "Beginning Drawing Atelier",
    author: "661f3954d8592757e2c7fc11",
    reviews: 661,
    cover: "hard cover",
    image: "beginning.jpg",
    printLength: 128,
    language: "English",
    PublicationDate: "16 April 2018",
    inStock: false,
  },
];

const authors = [
  {
    id: 1,
    name: "Nizar Qabbani",
    image: "/authors/nizar.jpg",
  },
  {
    id: 2,
    name: "Mahmoud Darwish",
    image: "/authors/darwish.jpg",
  },
  {
    id: 3,
    name: "Tony Robbins",
    image: "/authors/tony.jpg",
  },
  {
    id: 4,
    name: "Elif Shafak",
    image: "/authors/shafak.jpg",
  },
  {
    id: 5,
    name: "Brian Tracy",
    image: "/authors/brain.jpg",
  },
  {
    id: 6,
    name: "Nassim Nicholas Taleb",
    image: "/authors/nassim.jpg",
  },
  {
    id: 7,
    name: "Khalil Gibran",
    image: "/authors/khalil.jpg",
  },
  {
    id: 8,
    name: "Debbie Ford",
    image: "/authors/ford.jpg",
  },
  {
    id: 9,
    name: "Paulo Coelho",
    image: "/authors/paulo.jpg",
  },
  {
    id: 10,
    name: "Wayne Dyer",
    image: "/authors/wayne.jpg",
  },
  {
    id: 11,
    name: "Albert Camus",
    image: "/authors/albert.jpg",
  },
  {
    id: 12,
    name: "George Orwell",
    image: "/authors/george.jpg",
  },
  {
    id: 13,
    name: "Robert Kiyosaki",
    image: "/authors/kiyosaki.jpg",
  },
  {
    id: 14,
    name: "Warren Buffett",
    image: "/authors/buffett.jpg",
  },
  {
    id: 15,
    name: "Ernest Hemingway",
    image: "/authors/eh.jpg",
  },
  {
    id: 16,
    name: "Mark Twain",
    image: "/authors/mark.jpg",
  },
  {
    id: 17,
    name: "Xavier Crement",
    image: "/authors/crement.jpg",
  },
  {
    id: 18,
    name: "Rolf Dobelli",
    image: "/authors/rolf.jpg",
  },
  {
    id: 19,
    name: "George Samuel Clason",
    image: "/authors/clason.jpg",
  },
  {
    id: 20,
    name: "Phil Knight",
    image: "/authors/phil.jpg",
  },
  {
    id: 21,
    name: "Oscar Wilde",
    image: "/authors/oscar.jpg",
  },
  {
    id: 22,
    name: "James Clear",
    image: "/authors/james.jpg",
  },
  {
    id: 23,
    name: "Colleen Hoover",
    image: "/authors/hoover.jpg",
  },
  {
    id: 24,
    name: "Sajni Patel",
    image: "/authors/patel.jpg",
  },
  {
    id: 25,
    name: "Taylor Jenkins Reid",
    image: "/authors/reid.jpg",
  },
  {
    id: 26,
    name: "Napolen Hill",
    image: "/authors/hill.jpg",
  },
  {
    id: 27,
    name: "Chris Voss",
    image: "/authors/voss.jpg",
  },
  {
    id: 28,
    name: "Vex King",
    image: "/authors/king.jpg",
  },
  {
    id: 29,
    name: "Juliette Aristides",
    image: "/authors/j.jpg",
  },
  {
    id: 30,
    name: "Leo Tolstoy",
    image: "/authors/leo.jpg",
  },
];

module.exports = {
  books,
  authors,
};
